### ISSUE TITLE
Can you please help me, I'm having the same issue

### ISSUE THREAD

**Issue by ristovskiv** [d-nation/highstock-rangeinput-example#1]
I'm having the same issue as here http://forum.highcharts.com/highstock-usage/unable-to-change-from-and-to-dates-t15725/ . Have you found a workaround for this, and can you please help? I'm using plain backbone without marionette js.

**Comment by ristovskiv** [comment]
Nevermind, I've solved it. Thanks anyway, the post helped me :dancer:

**Comment by d-nation** [comment]
Awesome, I was just about to respond. Glad you got it sorted :+1:  :beers:
